alandtse/alexa_media_player

LICENSE
Update of license to Apache 2.0
=> migrate to apache 2.0

media_player/alexa.py
Fixes #10 by explicitly checking for the device json.  Still may make sense to have every API call check that the log-in is still valid although the use of cookies may moot that.
This contains other fixes and improvements. 
1.  Lxml was not in the requirements.
2. Captcha had a typo in the configurator.
3. session.[mainArt][url] had a keyerror. Added a check for key existence before assignment.
4. Saving of session cookies.
5. More debug logs.
6. Configurator failure message and explanation on what to do with blank images.
EDIT: Added more features and updated the PR description.
=> Fixes for JSONDecodeError and other misc issues.

media_player/alexa.py
Existing cookies appear to be accepted even swapping on 2FA so testing will require deleting the cookie.
=> Adding 2FA

media_player/alexa.py
=> Adding existence checks for nested dictionaries.

media_player/alexa.py
The rest API uses a different sign-in site then we were using to sign-in.  So to resolve the remaining sign-in issue, this version uses the Alexa sign-in instead of the general sign-in page.  
This adds an extra attempt to log in because based on testing the Alexa site was rejecting the first programmatic log in. I think the extra attempt may resolve the issue some were experiencing with infinite captchas even with the general sign-in page but that hasn't been tested.
=> Switch login site to Alexa sign-in site

media_player/alexa.py
=> Add checking for nested dictionaries for media state

media_player/alexa.py
=> Fix handling of bad cookie to attempt credential login

media_player/alexa.py
=> Fix get_bluetooth to use .json exception catching in AlexaAPI

media_player/alexa.py
Keaton,
I got tired of seeing a bunch of extra devices in my list of Alexa devices so I added the ability to specify an include or an exclude list of devices by name.  This is my first time ever doing a pull request (in my professional life I work with Visual Studio Online so my Git experience is limited) so let me know if I did it wrong.
Chris
=> Implement include/exclude device lists

media_player/alexa.py
Bumping version because of new last_call attribute feature
=> Bump version

media_player/alexa.py
This resolves #68. 
Signed-off-by: Alan Tse <alandtse@gmail.com>
=> Fix typo in last_activity call

media_player/alexa.py
=> Fix HA 0.88.0 architecture change

alexa_media/media_player.py
=> Fix display of media position while playing

alexa_media/__init__.py, alexa_media/const.py, alexa_media/media_player.py, custom_components.json
=> Add custom_updater support

alexa_media/__init__.py
=> Fix bug where configurator would fail if no options for verification method

alexa_media/__init__.py, alexa_media/const.py, alexa_media/media_player.py
=> Update to alexapy 0.2.1

alexa_media/__init__.py, alexa_media/media_player.py, alexa_media/notify.py, custom_components.json
This enables the [notification service](https://github.com/keatontaylor/alexa_media_player/wiki/Notification-Component). (resolves #51)
**Warning:** `media_player.alexa_tts` will be deprecated in the next version.
=> Update to 1.2.0

alexa_media/__init__.py, alexa_media/media_player.py, alexa_media/notify.py, custom_components.json
* Add initial notify service with working tts
* Add announcement notify feature
* Change logging level for messages
* Add mobilepush functionality
* Bump version
* Add group support to notify
* Fix pylint errors
* Bump custom_component version
* Resolves #51
=> Update to 1.2.0 (#110)

alexa_media/__init__.py, alexa_media/notify.py, custom_components.json
Fix bugs related to generation of targets for announce (resolves #114, #117, #118)
=> Update to 1.2.1

alexa_media/__init__.py, custom_components.json
* Fix bug where polling would not resume after websocket failure (resolves #128)
* Update to alexapy 0.4.2 (resolves #127)
=> Update to 1.2.3

alexa_media/__init__.py, custom_components.json
- Fix bug where polling would not resume after websocket failure (resolves #128)
- Update to alexapy 0.4.2 (resolves #127)
=> Update to 1.2.3 (#131)

alexa_media/__init__.py, alexa_media/media_player.py
=> Add support for updating the players online state from websocket messages

alexa_media/__init__.py, alexa_media/media_player.py
Added updating bluetooth devices from WebSocket messages. Looks like for every single PUSH_BLUETOOTH_STATE_CHANGE the https://alexa.amazon.com website pulls the bluetooth state information so if they're doing it I don't think we need to mess with narrowing down the call a bit more. If we hit rate limits or users have issues we can tidy it up.
=> Bluetooth Websocket 

alexa_media/__init__.py, alexa_media/const.py, alexa_media/notify.py
Addresses #137 
You should remove any existing Notify config.
=> Allow autoloading of notify component

alexa_media/__init__.py, custom_components.json
- Bumps alexapy version (fixes #145)
- Adding dev version for custom_updater (fixes #143)
- Bumps version for next release
=> Update dev to 1.2.4

alexa_media/__init__.py, alexa_media/const.py, alexa_media/media_player.py, alexa_media/notify.py, custom_components.json
Features:
- Add automatic target generation for notify component service
Fixes:
- Fix bug where existing media players would be added again on reconnect (resolves #136)
- Fix bug where routines would not be found when many routines exist (resolves #145)
Changes:
- Update online/active based on DOPPLER_STATE_CHANGE from websockets (resolves #133)
- Update bluetooth state based on websockets (resolves #135)
- Update new devices based on websockets
- Change notify component to autoload - **You may have to remove existing notify configuration to avoid _2 service**
- Add dev branch to custom_updater (resolves #143)
- Update to alexapy 0.4.3 (resolves #145)
=> Update master to 1.2.4

alexa_media/media_player.py
=> Change source_list to return bluetooth profiles with A2DP-SOURCE

alexa_media/manifest.json, alexa_media/services.yaml
Fixes #164.
While targeting dev, I'd suggest deleting dev and rebasing on master so not to complicate the history.
=> Add files for HA 0.92.0

README.md, alexa_media/__init__.py, alexa_media/media_player.py
=> Add locale checking based on devicePreferences

README.md, alexa_media/__init__.py, alexa_media/manifest.json, alexa_media/media_player.py, alexa_media/services.yaml, custom_components.json
Features:
- None
Fixes:
- Add files required for HA 0.92.x (resolves #164)
- Fix bug where all bluetooth devices listed as sources (resolves #166 )
- Fix bug where nested nodes in Hue scenes would not run (resolves #156 )
Changes:
- Populate locale based on device preferences (resolves #79)
- Remove dev branch from custom_updater as this was hard to maintain (resolves # 159)
- Update to alexapy 0.5.0 (resolves #156)
- Update README configuration section to reference Wiki
=> Update to 1.2.5

custom_components.json
=> Add missing new files for custom_updater

alexa_media/__init__.py
Fixes #181. Requires alexapy update from same named branch
=> Add reconnect logic for websocket

alexa_media/media_player.py
=> Add check for existing entity

alexa_media/__init__.py
=> Remove references to async

custom_components/alexa_media/media_player.py
=> fix(media_player): remove unused MEDIA_PLAYER_SCHEMA

custom_components/alexa_media/media_player.py
=> fix(media_player): alternative serial numbers not recognized for mobile app media player

custom_components/alexa_media/alarm_control_panel.py
=> fix(guard): catch additional out of region exceptions

custom_components/alexa_media/__init__.py, custom_components/alexa_media/alarm_control_panel.py
=> fix(guard): add 1s delay for guard state check after voice activity

custom_components/alexa_media/__init__.py, custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
=> fix: handle Amazon API login changes

custom_components/alexa_media/__init__.py, custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/switch.py
=>  feat(switches): add switches for shuffle, dnd, and repeat

custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/switch.py
=> Bump to 1.4.1

custom_components/alexa_media/__init__.py, custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py, custom_components/alexa_media/switch.py
Resolves #282 
BREAKING CHANGE: requires new alexapy
=> feat: migrate to async

custom_components/alexa_media/__init__.py
=>  fix(bluetooth): check for valid response from get_bluetooth

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py
=> fix(bluetooth): resolve bluetooth update issues

hacs.json
=> chore: add hacs.json

custom_components/alexa_media/notify.py
=> fix(notify): add key check for targets

custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/switch.py
=> fix: add checks for self.enabled prior to HA updates

custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/switch.py
Reverts custom-components/alexa_media_player#327
Requires HA 98.1 so should wait a bit
=> Revert "fix: add checks for self.enabled prior to HA updates"

.github/ISSUE_TEMPLATE/bug_report.md, custom_components/alexa_media/__init__.py
=> fix: clean discovery_info of unneeded values prior to passing

custom_components/alexa_media/helpers.py
=> fix(helpers): correctly treat add_devices with empty list as non error

custom_components/alexa_media/config_flow.py
=> fix(config_flow): fix handling of filter options

.github/workflows/semantic_release.yml
Signed-off-by: Alan Tse <alandtse@gmail.com>
=> ci: add semantic-release

custom_components/alexa_media/__init__.py, custom_components/alexa_media/helpers.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/switch.py
=> fix: add retry logic to setup_entry

custom_components/alexa_media/manifest.json
=> fix: bump alexapy to 1.2.1

LICENSE, custom_components/alexa_media/.translations/en.json, custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py, custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py, custom_components/alexa_media/strings.json
Fixes #387 
Requires [alexapy update](https://gitlab.com/keatontaylor/alexapy/merge_requests/82/).
=> fix: fix config_flow connection handling

LICENSE, custom_components/alexa_media/.translations/en.json, custom_components/alexa_media/__init__.py, custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/config_flow.py, custom_components/alexa_media/const.py, custom_components/alexa_media/helpers.py, custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py, custom_components/alexa_media/sensor.py, custom_components/alexa_media/strings.json, custom_components/alexa_media/switch.py, hacs.json
Resolves #144
Requires [alexapy dev branch](https://gitlab.com/keatontaylor/alexapy/tree/dev)
=> feat: add alexa notifications as sensors

custom_components/alexa_media/__init__.py
=> fix(sensor): fix missing music alarms

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/sensor.py
=> fix(sensor): set timezone of naive date_time alarms

custom_components/alexa_media/__init__.py, custom_components/alexa_media/manifest.json
Requires [new alexapy](https://gitlab.com/keatontaylor/alexapy/merge_requests/89)
Closes #397, Closes #401, Closes #406
=> fix(websocket): fix reconnect on disconnect

custom_components/alexa_media/config_flow.py
Requires alexapy update.
Fixes #401
=> fix(config_flow): display claimspicker_message correctly

custom_components/alexa_media/const.py, custom_components/alexa_media/helpers.py
=> fix(helpers): fix key error during login exception

custom_components/alexa_media/const.py, custom_components/alexa_media/sensor.py
=> fix: change return state to avoid Invalid Date

custom_components/alexa_media/__init__.py, custom_components/alexa_media/const.py
=> fix: replace non-async configurator call

custom_components/alexa_media/__init__.py, custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py
=> fix: change availability when websocket detected

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py
=> fix: fix seen_command testing for manual refresh

custom_components/alexa_media/const.py, custom_components/alexa_media/sensor.py
=>  fix(sensor): handle devices without timezone settings

custom_components/alexa_media/const.py, custom_components/alexa_media/sensor.py
=> fix: use HA STATE_UNAVAILABLE for empty sensors

custom_components/alexa_media/alarm_control_panel.py
=> fix(alarm_control_panel): add supported_features

custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/sensor.py
=>  fix(alarm_control_panel): add supported_features

custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/manifest.json, hacs.json
=> fix: restore compatibility for older HA versions

custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
=> feat: add alexa sound to play_media

custom_components/alexa_media/media_player.py, custom_components/alexa_media/switch.py
=> fix: add additional catches for login errors

custom_components/alexa_media/media_player.py
=> fix(media_player): fix propagation of whole audio groups

custom_components/alexa_media/sensor.py
=> fix (sensor): add checks for timer values

custom_components/alexa_media/media_player.py
Change the var trigger for children refreshing to be isPlayingInLemur
Closes #472
=> fix(media_player): fix refresh of WHA children

custom_components/alexa_media/__init__.py, custom_components/alexa_media/alarm_control_panel.py, custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/sensor.py, setup.cfg
Includes miscellaneous other fixes
=> feat: add offline device detection

custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
=> fix: bump alexapy to 1.4.1

hacs.json
=> Fix HACS installation/update with zip_release

custom_components/alexa_media/__init__.py, custom_components/alexa_media/manifest.json
=> fix: bump to alexapy 1.4.2

custom_components/alexa_media/media_player.py
=> fix(media_player): fix last_called not set false

custom_components/alexa_media/__init__.py
This is a command to delete recordings from Alexa.
Closes #527
=> fix: address PUSH_DELETE_DOPPLER_ACTIVITIES

custom_components/alexa_media/__init__.py, custom_components/alexa_media/sensor.py
=> fix: handle older alarm format and round timers to nearest second

custom_components/alexa_media/sensor.py
This includes fixes I forgot to push with #535
=> fix: fix localization of timers

custom_components/alexa_media/sensor.py, custom_components/alexa_media/switch.py
=> fix: load found devices when load delay required

custom_components/alexa_media/__init__.py
=> fix: ignore PUSH_CONTENT_FOCUS_CHANGE

README.md, custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py
=> fix: allow tts requests to be sent in parallel

custom_components/alexa_media/media_player.py
=> fix: quote pandora media urls

custom_components/alexa_media/sensor.py
The Alexa API apparently does not change the timer date until midnight but instead
relies on the client app to figure out the next alarm based on the
recurrence pattern. This adds that logic.
fixes #566
=> fix: fix next timer for recurrence alarms

custom_components/alexa_media/manifest.json
closes #587
closes #586
closes #544
=> fix: bump alexapy to 1.5.2

custom_components/alexa_media/sensor.py
Change RECURRING_PATTERN_ISO_SET to dict and also prevent unnecessary
loops if alarm is off.
fixes #596
=> fix: fix handling of weekly recurringPattern alarm

custom_components/alexa_media/sensor.py
=> fix: handle recurring reminders

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py
=> fix: abort websocket connections on EofStream

custom_components/alexa_media/__init__.py, custom_components/alexa_media/sensor.py
=> fix: address changes to notifications api

custom_components/alexa_media/__init__.py
This is to address changes to Alexa's API and the retirement of keys.
Closes #641
=> fix: add additional checks to notifications setup

.github/workflows/semantic_release.yml, custom_components/alexa_media/manifest.json
=> fix: bump alexapy to 1.7.1

custom_components/alexa_media/notify.py
=> fix(notify): fix use of wrong email variable

custom_components/alexa_media/manifest.json
This removes an extraneous volume call to try to fix too many requests.
closes #688
=> fix: bump alexapy to 1.8.2

custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
Please take a look at the wiki page https://github.com/custom-components/alexa_media_player/wiki#triggering-a-skill-versions--270 for more information
=>  feat: add ability to trigger a skill

custom_components/alexa_media/manifest.json
=> fix: bump alexapy to 1.8.3

custom_components/alexa_media/__init__.py
=> fix: add further session closed checks

custom_components/alexa_media/media_player.py
=>  feat: add attributes for bluetooth devices

custom_components/alexa_media/sensor.py
=> feat: add previous_value attrib for notifications

custom_components/alexa_media/media_player.py
=> fix: fix bug for null mainArt

custom_components/alexa_media/configurator.py
=> fix: initialize config_id in configurator

custom_components/alexa_media/__init__.py, custom_components/alexa_media/const.py, custom_components/alexa_media/notify.py
=> fix: load notify targets as json

custom_components/alexa_media/manifest.json
=> fix: bump alexapy to 1.10.3

custom_components/alexa_media/.translations/fr.json
=> French translation

custom_components/alexa_media/.translations/en.json, custom_components/alexa_media/config_flow.py, custom_components/alexa_media/configurator.py, custom_components/alexa_media/const.py, custom_components/alexa_media/manifest.json, custom_components/alexa_media/strings.json
=> Javascript auth page

custom_components/alexa_media/__init__.py
Polling would get set to scanning_interval on a reconnect and was
not properly updated on websocket_connect.
=> fix: update_coordinator polling on websocket

custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
https://github.com/custom-components/alexa_media_player/wiki#set-echo-show-background-versions--2100
=> feat: add ability to set Echo show background

custom_components/alexa_media/manifest.json
=> fix: bump alexapy to 1.12.1

custom_components/alexa_media/manifest.json, custom_components/alexa_media/sensor.py
HA apparently does not use semver.
closes #915
=> fix: remove use of semver

custom_components/alexa_media/manifest.json
=> fix: add packaging dependency

custom_components/alexa_media/.translations/de.json, custom_components/alexa_media/.translations/en.json, custom_components/alexa_media/.translations/es.json, custom_components/alexa_media/.translations/fr.json, custom_components/alexa_media/.translations/it.json, custom_components/alexa_media/.translations/nl.json, custom_components/alexa_media/.translations/pl.json, custom_components/alexa_media/.translations/ru.json, custom_components/alexa_media/.translations/zh-Hans.json, custom_components/alexa_media/config_flow.py, custom_components/alexa_media/strings.json
=> fix: replace `\n` with `<br />`

custom_components/alexa_media/sensor.py
See discussion https://github.com/custom-components/alexa_media_player/issues/964
=> Added process_timestamp attribute to notification sensors

custom_components/alexa_media/sensor.py
=> fix: convert reminder alarmTime when float

.github/workflows/validate.yaml
I recently announced ha-blueprint:
https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041?u=ktibow
This makes CI use it.
=> Use ha-blueprint

custom_components/alexa_media/config_flow.py
=> fix: fix key error on otp_secret

custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
This allows issuing commands to devices directly.
https://github.com/custom-components/alexa_media_player/wiki#run-custom-command
=> feat: add custom command support

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py, custom_components/alexa_media/const.py, custom_components/alexa_media/manifest.json, custom_components/alexa_media/media_player.py
The oauth refresh will only impact new logins. Please force logout with `alexa_media.force_logout` or delete your cookie file and restart.
closes #1005
=> fix: add oauth refresh

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py, custom_components/alexa_media/manifest.json
=> fix: fix oauth for non-.com domain

custom_components/alexa_media/manifest.json
=> fix: ensure string type for configflow

custom_components/alexa_media/media_player.py
Add check that event serial number matches before changing available
state
closes #1042
=> fix: fix erroneous available on websocket event

custom_components/alexa_media/media_player.py
Investigating a potential freeze
=> fix: change coordinator update to null operation

custom_components/alexa_media/notify.py
This reverts commit 717b7f7fea9a6cd8a990b750e35d76a5220a17ac.
=> revert: fix: fix entity name for unload

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py
This requires HA to allow dynamic targets.
closes #1104
=> feat: add last_called notify service target

custom_components/alexa_media/helpers.py
This would occur if more than one HA instance shared a uuid. This is a rare
occurence and would happen if you copied the complete config between
servers. However, this means the registered device name will change.
You can safely remove the older ones.
closes #1130
=> fix: fix deregistration for duplicate HA uuids

custom_components/alexa_media/notify.py
=> fix: fix announce for second account

custom_components/alexa_media/config_flow.py
If a user cancels setup through the UI, it is possible the proxy will remain
active until HA restart. This will now force the proxy to close after
10 minutes.
=> fix: cancel proxy after 10 minutes

custom_components/alexa_media/manifest.json
Fix to use latest automations url
closes #1149
=> fix: bump to alexapy 1.22.3

custom_components/alexa_media/media_player.py
=> fix: update last_update before notify update

custom_components/alexa_media/config_flow.py, custom_components/alexa_media/const.py, custom_components/alexa_media/manifest.json
This should allow https or using the external url.
closes #1167
=> feat: use HA view for proxy address

custom_components/alexa_media/config_flow.py
=> fix: handle case when hass has no detectable url

custom_components/alexa_media/manifest.json
Uncaught exception was incorrectly detecting a forced logout
closes #1207
=> fix: handle non-json domainAttributes in activities

custom_components/alexa_media/sensor.py
=> fix: use ha converter for local time

custom_components/alexa_media/manifest.json
=> fix: fix case where proxy receives ip address only

custom_components/alexa_media/alexa_entity.py
=> fix: check for existence of properties key

custom_components/alexa_media/translations/pt-br
brazilian portuguese localization
=> PT-BR localization

custom_components/alexa_media/manifest.json
This is a new requirement in HA revealed by hassfest.
=> fix: add iot_class to manifest.json

custom_components/alexa_media/__init__.py, custom_components/alexa_media/helpers.py, custom_components/alexa_media/sensor.py
Closes #1014. This does 4 things:
1. Add an event "alexa_media_alarm_dismissal_event" any time an alarm is dismissed.
2. Add a status attribute to notification sensors
3. Add a dismissed attribute to notification sensors. This includes all notification types. It is updated to the current time any time that sensor has its notification dismissed.
4. Change the alarm sensor so that a snoozed alarm is classified as "active".
4 is a small change in behavior. It seemed to make sense to me. A snoozed alarm is still active.
=> Add an event "alexa_media_alarm_dismissal_event"

custom_components/alexa_media/alexa_entity.py
Fixes #1275. It does this by expanding the checks of what is considered a local device while still excluding skill devices.
=> fix: improve checking for skill backed appliances

custom_components/alexa_media/__init__.py
=> fix: avoid pruning devices in secondary accounts

custom_components/alexa_media/alexa_entity.py
=> fix: comparison between offset-naive and offset-aware datetimes

custom_components/alexa_media/manifest.json
This was needed to make alexa media work in the newest home assistant
=> Home Assistant uses packaging~=21.0 now

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Add dev container files to allow easier development for those that are used to VScode self contained environment.
=> Add dev container management

custom_components/alexa_media/__init__.py
If there is a issue during login, raise `ConfigEntryNotReady` so core is instructed to retry in background.
Fixes #1529 
Simone
=> Introduce ConfigEntryNotReady

custom_components/alexa_media/config_flow.py
https://github.com/custom-components/alexa_media_player/issues/1512
I ran into this issue and this fixed it for me.
=> Fix cookie issues

custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
Fixes HA beta dependency conflict
closes #1579
=> fix: bump dependencies

custom_components/alexa_media/__init__.py
=> fix: remove CONF_OAUTH_LOGIN calls

custom_components/alexa_media/notify.py
Fix for https://github.com/custom-components/alexa_media_player/issues/1638.
Note that with the current system event notification processing order, the `elif` branch in the new code was never taken during my testing. But it seemed more robust to include this in case there is a scenario where it is taken (that I did not hit during my testing) or if the event processing order ever changes.
This is my first time writing any Python code in very many years, so apologies in advance if there's a better way of coding this.
=> Fix notify.alexa_media_last_called race condition

.pre-commit-config.yaml, custom_components/alexa_media/const.py, custom_components/alexa_media/sensor.py
Handle new Amazon reminder and alarm recurrence rules.
closes #1608
=> fix(notifications): handle new recurrence rules

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py
=> Config import fix

custom_components/alexa_media/sensor.py
=> fix(sensor): inherit from SensorEntity

.github/workflows/semantic_release.yml
https://github.com/relekang/python-semantic-release/issues/442
=> ci: freeze psr to v7.28.1

custom_components/alexa_media/__init__.py
=> fix: handle key errors due to bad alexa responses

custom_components/alexa_media/__init__.py, custom_components/alexa_media/alexa_entity.py, custom_components/alexa_media/binary_sensor.py, custom_components/alexa_media/const.py
* Add ZigBee contact sensors support
* Respect unavailable state of binary_sensor
* Add safe get of applianceTypes
Co-authored-by: Cosimo Meli <cosimo.meli@chili.com>
=> feat: Add ZigBee contact sensors support (#1754)

custom_components/alexa_media/notify.py
Closes https://github.com/custom-components/alexa_media_player/issues/1764
=> FIX New default tts missing

custom_components/alexa_media/notify.py
* FIX New default tts missing
* FIX if condition data
Co-authored-by: Carsten Docktor <carsten.docktor@fgh-zertifizierung.de>
closes #1764
=> fix(notify): handle null data key (#1767)

custom_components/alexa_media/sensor.py
Complete update to native_value units deprecated as of HA 2021.12.
closes #1824
=> fix: fix alarms, timers, and reminders

custom_components/alexa_media/sensor.py
=> fix: restore alexa_entity_id attribute

custom_components/alexa_media/sensor.py
=> fix: update coordinator callback to update sensors

custom_components/alexa_media/alexa_entity.py
Draft for a change which let alexa media player detect local ledvance bulbs #1839
=> fix: detect ledvance bluetooth bulbs #1839

custom_components/alexa_media/alexa_entity.py
=> feat: add ledvance bluetooth bulbs (#1847)

custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py
That should solve the issues: https://github.com/custom-components/alexa_media_player/issues/2022
=> Added correct path-creation using native HA methods

custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py
=> fix: use native HA methods to create paths (#2025)

custom_components/alexa_media/__init__.py, custom_components/alexa_media/manifest.json, custom_components/alexa_media/notify.py, poetry.lock, pyproject.toml
closes https://github.com/custom-components/alexa_media_player/issues/1982
closes https://github.com/custom-components/alexa_media_player/issues/1953
=> fix: fix http2 push for non-NA domains

custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
=> fix: bump alexapy to 1.27.4

custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
=> fix: bump alexapy 1.27.6

.github/workflows/semantic_release.yml, custom_components/alexa_media/const.py, custom_components/alexa_media/manifest.json, pyproject.toml
=> docs: fix version numbers

.pre-commit-config.yaml, custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
closes #2089
Thanks to @Fredo70
=> fix: bump alexapy to 1.27.7

custom_components/alexa_media/__init__.py
=> fix: Add timeout to last_called (#2140)

custom_components/alexa_media/media_player.py, hacs.json
=> fix: fix media player supported features for HA beta (#2150)

custom_components/alexa_media/__init__.py, custom_components/alexa_media/alexa_entity.py, custom_components/alexa_media/switch.py
=> feat: add support for Amazon Smart Plug (#2154)

custom_components/alexa_media/alarm_control_panel.py
=> fix: Fix deprecated alarm_control_panel constants

custom_components/alexa_media/light.py
Fix: Replaced invalid attribute reference ColorMode.HS_COLOR with correct attribute ColorMode.HS
to address #2185
=> fix: fix Color Mode Attribute

custom_components/alexa_media/light.py
=> fix: fix Color Mode Attribute (#2186)

custom_components/alexa_media/notify.py
Fixes https://github.com/alandtse/alexa_media_player/issues/2247.
=> fix: fix hass.component.group deprecation.

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py
Fixes deprecation warnings for async_add_job.
Fixes https://github.com/alandtse/alexa_media_player/issues/2225
partially fixes: https://github.com/alandtse/alexa_media_player/issues/2239
=> fix: fix deprecation of async_add_job

custom_components/alexa_media/__init__.py
add hide_serial for Debug Output
closes #2255
=> fix: add hide_serial for Debug Output

custom_components/alexa_media/light.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/sensor.py, custom_components/alexa_media/switch.py
=> fix: swap "async_write_ha_state" with "schedule_update_ha_state"

custom_components/alexa_media/sensor.py
Fixes #2277
Removed pytz and uses the HA dt methods instead.
=> fix: remove pytz to fix blocking

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py
Fix warning about awaiting `hass.config_entries.async_forward_entry_setup`.
=> fix: fix warning for async_forward_entry_setup

custom_components/alexa_media/__init__.py, custom_components/alexa_media/media_player.py, custom_components/alexa_media/notify.py
Apply bdraco's config entry suggestion.
=> Fix config entry setup

custom_components/alexa_media/__init__.py
=> fix: Raise ConfigEntryNotReady on timeout exception

custom_components/alexa_media/config_flow.py
=> fix: fix AttributeError for 'AlexaMediaFlowHandler'

custom_components/alexa_media/config_flow.py
=> fix: use `config_flow` in OptionsFlow Handler(#2343)

custom_components/alexa_media/sensor.py
Remove `@callback`
Change `hass.bus.async_fire` to `hass.bus.fire`
=> fix: apply correct fix for threading warning

custom_components/alexa_media/__init__.py
Fixes undefined error line 649: `except (asyncio.TimeoutError, TimeoutException) as ex`
=> fix: fix undefined TimeoutException

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py
Also added ability to reconfigure the CONF_PUBLIC_URL
Should resolve issues #2369 & #2130
=> fix: fix CONF_PUBLIC_URL saving

custom_components/alexa_media/__init__.py
=> fix: fix typo in import (#2384)

custom_components/alexa_media/__init__.py
=> fix: replace deprecated hass.components usage (#2390)

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py
Also fixes a typo in __init__.py in PR #2390 / #2391
=> fix: replace deprecated hass.components usage (config_flow.py)

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py
=> fix: config_flow.py - 2nd CONF_URL s/b CONF_HASS_URL

custom_components/alexa_media/config_flow.py
Reverts alandtse/alexa_media_player#2397
=> revert: "fix: config_flow.py - 2nd CONF_URL s/b CONF_HASS_URL"

custom_components/alexa_media/__init__.py, custom_components/alexa_media/config_flow.py
Reverts alandtse/alexa_media_player#2396
=> revert: "fix: replace deprecated hass.components usage"

custom_components/alexa_media/config_flow.py
Removed self.config.pop("hass_url")
Fixes #2408
=> fix: fix hass_url undefined

custom_components/alexa_media/config_flow.py
=> fix: async_dismiss_persistent_notification missing positional argument: notification_id

custom_components/alexa_media/config_flow.py
Fixes [issue #2575](https://github.com/alandtse/alexa_media_player/issues/2575)
=> fix: ensure public_url ends with trailing slash

CHANGELOG.md, custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
=> fix: bump alexapy to 1.29.3 (#2634)

custom_components/alexa_media/__init__.py
This should fix issue [not able to install - failing at final step (KeyError: 'public_url') #2554](https://github.com/alandtse/alexa_media_player/issues/2554)
=> fix: missing public_url

custom_components/alexa_media/__init__.py
Reverts alandtse/alexa_media_player#2670
=> revert: "fix: missing public_url"

custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
Changelog: https://gitlab.com/keatontaylor/alexapy/-/releases/v1.29.5
Closes: #2723 
Closes: #2720
Closes: #2698
=> fix: bump alexapy to version 1.29.5

custom_components/alexa_media/manifest.json, poetry.lock, pyproject.toml
Closes #2723
Closes #2720
Closes #2698
=> fix: bump alexapy to version 1.29.5 (#2724)

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .pre-commit-config.yaml
Install pre-commit hooks into dev container
=> chore: install precommit when working in dev container

custom_components/alexa_media/const.py, custom_components/alexa_media/media_player.py
=> fix: clarify error message for music streaming (#2736)

custom_components/alexa_media/config_flow.py
=> fix: sets option flow config_entry explicitly [deprecation warning]

custom_components/alexa_media/__init__.py, custom_components/alexa_media/helpers.py, custom_components/alexa_media/media_player.py
=> feat: support `NotifyNowPlayingUpdated` pushes (#2827)

custom_components/alexa_media/media_player.py
`_attr_supported_features` is dynamically configured according to the playback content, and UI components that cannot be controlled are not displayed.
=> feat: dynamically configuring _attr_supported_features

custom_components/alexa_media/media_player.py
Cleaned up and optimized import statements.
=> refactor: optimizing imports

custom_components/alexa_media/media_player.py
This may resolve issues #2868, #2889.
I haven't had the reported issues yet, so this needs validation from someone who does.
=> fix: fixed volume, supported_features issue in Version 5.5-6

custom_components/alexa_media/__init__.py
closes #2940
closes #2932
closes #2934
closes #2942
=> fix: remove deprecated call to get_network_details (#2943)

custom_components/alexa_media/alexa_entity.py
=> fix: device bridge retrieval structure (#2969)
