alandtse/alexa_media_player

media_player/alexa.py

Should resolve #33.
Also minor fixes:
- Add debug option - This adds a debug option for sensitive data. It will actually write debug html files to the config directory and output emails/passwords to the debug log. While I recognize HA already has logger debug levels, I wasn't comfortable shipping a default version that would log passwords into HA. Should be easy to rip out, but I'm forced to manually add it in when I debug so I'd prefer to keep it.
- Fix modal orphan bug - This happens when we done a configurator before it closes.
- Capture Amazon error message to log and configurator
- Detect later Amazon login failure and automatically attempt relogin. Should address PR #32.
- Refactor login status testing code
- Minor fixes like updating user-agent

Handle Amazon verification pages

---

media_player/alexa.py

~~This should address #26~~
Since all devices are autodiscovered, it didn't make sense to create a per device filter in the configuration.  
~~This also enables a new optional configuration option which is by default on to only show online devices.~~
`media_player:
- platform: alexa
email: !secret amazon_user
password: !secret amazon_pass
url: amazon.com
onlineonly: True`

Refresh only online devices

---

.gitignore
media_player/alexa.py

Following [these instructions](https://stackoverflow.com/a/9646323) I reset my repository, reapplied [`git config core.filemode false`](https://stackoverflow.com/a/1257613), then pasted my changes back into .gitignore + alexa.py.
Hopefully this puts the repo in a better state for you to work with.

adding last_called

---

alexa_media/__init__.py
alexa_media/media_player.py

This should resolve #88. 
Waiting on reporter to test before merging.

Truncate event_bus data to 32 chars

---

.gitmodules
README.md
alexa_media/__init__.py
alexa_media/media_player.py
custom_components.json

Fixes:
- Fix bug where emulated_hue and other smart home device routines failed. (resolves #123) 
- Fix bug where Alexa devices that came online later were not properly updated. (resolves #125)
Changes:
- Add websocket support (resolves #119) - This allows us to remove most polling and rely on push notifications from Amazon. This also means that media_players should update **regardless** of how or where you interact with them as `last_called` should update immediately. As a result `alexa_media.update_last_called` service may no longer be required. Prior polling methods remain as a fallback mechanism if websocket can't connect which may be based on region. No additional configuration is needed.
- Update to alexapy 0.4.0 (websocket support)
- Remove alexapy submodule from repo

Update to 1.2.2

---

alexa_media/__init__.py
alexa_media/media_player.py

Per our discussion in #132, this completely disables polling if websocket is detected. It also will do new device detection based on websockets. Should resolve #132. 
It does **not** handle bluetooth changes so is not a complete fix until your bluetooth update changes are merged in.  In theory you could simply force update_devices(no_throttle=True) after setting the `new_devices` key I mentioned in the other thread and the bluetooth update will be done as well.  Alternatively, you could move the bluetooth update over to it's own function which you would then call.
Also added some miscellaneous changes:
- Fix bug where reconnects would add known devices again (fix #124)
- Fix use of DATA_ALEXAMEDIA instead of DOMAIN to comply with HA requirements data store requirements
- Fix bug where …

Merge alandtse/dev

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
custom_components/alexa_media/__init__.py
custom_components/alexa_media/alarm_control_panel.py
custom_components/alexa_media/const.py
custom_components/alexa_media/manifest.json
custom_components/alexa_media/media_player.py
custom_components/alexa_media/switch.py

Features:
feat(switch): add basic switch support (do not disturb, repeat, shuffle) (resolves #195, resolves #203)
Fixes:
fix(media_player): remove unused MEDIA_PLAYER_SCHEMA (#261) (resolves #259)
fix(media_player): alternative serial numbers not recognized for mobile apps (resolves #249)
fix(guard): catch TypeError exception for regions without Guard (#245) (fixes #243, fixes #248 ) 
fix(guard): add additional checks for failed guard access (fixes #243, fixes #248 ) 
fix(guard): add 2s delay for guard state check after voice activity (fixes #256) 
fix(guard): schedule HA update after processing voice (fixes #256) 
fix(media_player): fix bug where get_last_called called before init
fix(captcha): add captcha to handle OTP selection page (fixes #258)
fix(wshandler): properly handle entryId …

Update to 1.4.0

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/alarm_control_panel.py
custom_components/alexa_media/helpers.py
custom_components/alexa_media/media_player.py
custom_components/alexa_media/switch.py

fix: add catch for HomeAssistantError when adding entities

---

custom_components/alexa_media/helpers.py
custom_components/alexa_media/notify.py
custom_components/alexa_media/switch.py

This will allow platforms to wait for media_player to load before trying to load. This will also fix various race conditions.

fix: add retry_async wrapper to automatically retry after failures

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/const.py
custom_components/alexa_media/media_player.py

German users reported that updates were failing and investigation
determined that websockets was missing push information on audio
changes. This adds logic to use other websocket push events to try to
compensate.
However, this is a degraded functionality and results in additional
refresh calls.
Closes #397

fix: add fallback for media refresh

---

custom_components/alexa_media/sensor.py

This resolves issue #446, which had Safari displaying "Invalid Date"
instead of a proper countdown. The strings were being rendered using
Python's default datetime renderer, which did not put a "T" in between
the day and the hour, as required by ISO-8601 (and Safari's Date()
parser, but not Chrome's)

fix(sensor): return all sensor states as isoformat strings

---

custom_components/alexa_media/media_player.py

This addresses a case where the parent group has not been loaded prior to an
update of a child media player.
Closes #496

fix: add check for loaded parent

---

custom_components/alexa_media/media_player.py

This increases the delay before a refresh of player state based on
change detection. This also agressively clears player data if Amazon
ever returns null data.
Closes #475

fix(media_player): fix clearing of data on state change

---

custom_components/alexa_media/manifest.json

fix: bump alexapy to 1.5.1

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/media_player.py

Certain push activities will clear the media state so must be checked.
closes #617

fix: force refresh on active media players on push

---

custom_components/alexa_media/switch.py
custom_components/alexa_media/translations

fix: catch missing key for switches dictionary

---

custom_components/alexa_media/.translations/en.json
custom_components/alexa_media/__init__.py
custom_components/alexa_media/alarm_control_panel.py
custom_components/alexa_media/config_flow.py
custom_components/alexa_media/const.py
custom_components/alexa_media/manifest.json
custom_components/alexa_media/media_player.py
custom_components/alexa_media/notify.py
custom_components/alexa_media/strings.json

Queue delay controls how long each command will wait to queue up other
commands. This will help reduce `too many requests` errors but will delay
running the command. The default is 1.5 seconds. 0 seconds will result in no
queuing behavior.

feat: add option for queue_delay

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/const.py

The import will now search config entries by data values instead of by title which
can be changed in HA 109. The code also properly creates a new entry
after failing a search.
closes #665

fix: fix configuration.yaml import code

---

custom_components/alexa_media/manifest.json
custom_components/alexa_media/media_player.py

This is the routine Stop Audio command which should stop all audio
including skills and is queueable. Use with `media_player.media_stop`
closes #692

feat: add media_stop command

---

custom_components/alexa_media/manifest.json

Canned TTS must begin with `alexa.cannedtts.speak` using the tts notify
mode. This is discovered using [sequence discovery](https://github.com/custom-components/alexa_media_player/wiki/Developers%3A-Sequence-Discovery).
closes #573

feat: add support for canned_tts

---

custom_components/alexa_media/alarm_control_panel.py
custom_components/alexa_media/media_player.py
custom_components/alexa_media/switch.py

Fixes per https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/
closes #699

fix: fix HA warning re deprecated classes

---

custom_components/alexa_media/__init__.py

This is intended to eventually replace alexa_media_player/relogin_required
which appears to cause issues in testing through the HA UI

fix: fire `alexa_media_player_relogin_required`

---

custom_components/alexa_media/__init__.py

async_fire is not a coroutine and would cause a TypeError when a relogin
was required
closes #867

fix: fix TypeError on use of async_fire

---

custom_components/alexa_media/manifest.json

This fixes an issue where we were using the ownerId for permissions.
This could result in permission errors if the logged in user was
different from the device owner. We are now only using the logged
in user.  While my testing didn't see anything wrong, this was an
extensive update so please report if any features may have broken.
closes #848

fix: bump alexapy to 1.13.0

---

custom_components/alexa_media/strings.json

got this warrning "Warning: G] [TRANSLATIONS] config.title key has been moved out of config and into the root of strings.json. Starting Home Assistant 0.109 you only need to define this key in the root if the title needs to be different than the name of your integration in the manifest."

fix: update strings.json to remove title key

---

custom_components/alexa_media/manifest.json

Handle `extra` keyword arg from HA 0.115.4
closes #957

 fix: bump to alexapy 1.15.2

---

.github/workflows/semantic_release.yml

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Signed-off-by: Alan Tse <alandtse@gmail.com>

ci: update release variable

---

.github/workflows/validate.yaml

Use an older version of Python to fix flake8

---

custom_components/alexa_media/__init__.py

Added capability check for TIMERS_AND_ALARMS and REMINDERS.
Include_devices will also override the capability check.
closes #1085

fix: allow devices with notification capability

---

custom_components/alexa_media/notify.py

Secondary accounts have a different unique_id so would fail to match
during convert. Add match on device_serial_number.
closes #1116

fix: fix target matching for secondary accounts

---

custom_components/alexa_media/config_flow.py
custom_components/alexa_media/strings.json
custom_components/alexa_media/translations/en.json

The server will now try to connect to the provided HA url. This will
catch basic errors related to the wrong ip addres or port or the use of
https. It will not catch firewall issue which are not detectable from
the server.

fix: check for valid ha url

---

custom_components/alexa_media/media_player.py

Follow up to #1178, this creates a background task in which AlexaAPI communicates with the device, that way we can leverage queue_delay to batch successive calls.
Tested using the following script:
```yaml
alias: Alexa Good Morning
sequence:
- service: notify.alexa_media
data:
message: Good morning Adrien! Your coffee is brewing.
data:
type: tts
target:
- media_player.living_room_echo_dot
- service: media_player.play_media
data:
entity_id: media_player.living_room_echo_dot
media_content_id: Alexa.Weather.Play
media_content_type: sequence
- service: notify.alexa_media
data:
message: Hope you have a wonderful day!
data:
type: tts
target:
- media_player.living_room_echo_dot
mode: single
```
Relevant part of the log showing the proper batching: 
```yaml
2021-02-13 15:45:08 DEBUG (MainThread) …
```

Wrap calls to AlexaAPI in async_create_task

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/manifest.json

Activites page may return {"message":"Rate exceeded"} with a http 200
message.
closes #1196

fix: ignore typerrors for update_last_called

---

custom_components/alexa_media/media_player.py

The use of async_create_task requires entity has been added to hass. If this
has not occured use the old direct call.
closes #1221

fix: check for hass existence and fallback call

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/alarm_control_panel.py
custom_components/alexa_media/alexa_entity.py
custom_components/alexa_media/config_flow.py
custom_components/alexa_media/const.py
custom_components/alexa_media/light.py
custom_components/alexa_media/sensor.py
custom_components/alexa_media/strings.json
custom_components/alexa_media/translations/en.json

Closes #1237 and #1202.
This moves all of the phoenix calls being done by the alarm platform into the data update coordinator so that sensor/light platform can share. This involved refactoring of the guard code.
Device support intentionally excludes all Skill-based devices Alexa has access to as there is likely another Home Assistant integration that can better address those items. The light support is quite limited supporting only brightness and power state. Temperature sensor support is complete, but is restricted specifically to the sensor built-in to an Echo.
With the exception of the new guard code, everything should be hidden by a new option. Enabling this feature requires turning that option on and reloading the integration.
I assume there are likely changes needed here. In …

Support lights and the temperature sensor of the Echo device

---

custom_components/alexa_media/__init__.py

As the title says, simplify the experience by auto-reloading. I'll update wiki when this merges.

Automatically reload the integration when extended entity discovery is enabled

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/alexa_entity.py
custom_components/alexa_media/light.py

Fixes #1251. This should do a reasonable job of ignoring lights that originated at emulated_hue. Sadly, after much testing Alexa eventually had my real Hue bulb and the emulated hue bulb identical in every way except manufacturer name.
I'll document the restriction that older Hue bulbs may be ignored if you have emulated_hue enabled.

Detect and ignore lights created by emulated_hue

---

custom_components/alexa_media/alexa_entity.py
custom_components/alexa_media/light.py

Closes  #1264. Add color and color temperature support for lights, plus this makes the UI feel more responsive in general by skipping some refreshes when possible.
The biggest issue I have here is a question about what minimum version of HA does AMP target? HA currently requires color supported to be advertised as both a supported_feature(partially deprecated) and as a supported_color_mode(2021.4+). The color_mode support is new in 2021.4. The hacs.json shows "0.106.0", but the poetry.lock is bringing in 2021.4.
I'm fully supporting both ways of reporting colors, so I all I really need in 2021.4 is a handful of string constant imports. I could hard code those if 0.106 is the correct minimum version.

Make lights controls more responsive and support colors

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/light.py
custom_components/alexa_media/sensor.py

Fixes #1289 by forcing all entity state to be gathered during network discovery discovery.
Previously, each platform forced a refresh on the coordinator. This was slow and error prone. Now, when the network is discovered full entity state is discovered as well.

Alarm state on startup instead of on first refresh

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/light.py
custom_components/alexa_media/sensor.py

Previously, each platform forced a refresh on the coordinator. This was slow and error prone. Now, when the network is discovered full entity state is discovered as well.
Fixes #1289

fix: update entity state after network discovery (#1291)

---

custom_components/alexa_media/alexa_entity.py

This also changes the entity parsing code to be extremely defensive so that this function won't break startup no matter what Amazon returns.
I have tested this as thoroughly as possible. It does not make anything worse and I'm 99% sure it fixes the bug. That missing 1% is because I had to fake this state in code because there doesn't appear to be a way to turn off Alexa Guard once its enabled on your account. I have requested help testing on the issue and hopefully someone can give me confirmation there,

Fixes #1296 by not contacting Alexa with an empty list of entities.

---

custom_components/alexa_media/alexa_entity.py

This relies on pulling the timestamp from the string instead of defaulting to UTC
closes #1350

fix: parse timezone from timestamp

---

custom_components/alexa_media/config_flow.py

Sets a default dictionary key even during reauth.
closes #1419

fix: set default `accounts` key in dictionary

---

custom_components/alexa_media/config_flow.py

This fixes the case of switching from legacy to proxy login method.
closes #1418
closes #1318

fix: fix conversion of aiohttp cookie to httpx

---

hacs.json

Due to changes in aiohttp dependency in HA and alexa_media, need to bump
the HA requirement.
closes #1434

fix: require 2021.12.0

---

custom_components/alexa_media/switch.py

In a recent release, HA added the concept of entity categories, distinguishing between primary, configuration, diagnostic, and system entities.
This PR just tags the relevant AlexaMediaSwitches as config entities (since they modify configurable toggles rather than primary media player functionality (DND, Shuffle, Repeat). This shouldn't have any substantial impact other than cleaning up some of the auto-generated HA dashboards, and how things are visualized in the UI. I think it will also allow these switches to be filtered in templates if users only want to flip "primary" switches and not configuration switches in an area.
Some additional docs on this are available here:
Release Announcement: https://www.home-assistant.io/blog/2021/11/03/release-202111/
Developer Blog: …

Add entity_category to the AlexaMediaSwitches

---

custom_components/alexa_media/switch.py

Specifying the entity category as a string doesn't work anymore starting in `2022.4`, you must use the `EntityCategory` enum instead. This fixes #1553 
The enums have been accepted since `2021.12` ([PR](https://github.com/home-assistant/core/pull/60720)) which covers your supported versions so it is safe to make immediately, don't have to wait for `2022.4`.

Use EntityCategory enum instead of strings

---

custom_components/alexa_media/config_flow.py

Resets all cookies when loading the proxy. However, this removes the ability to start a login using the legacy method (including relogin attempts) and then resuming them with the proxy.
closes #1512

fix: reset cookies on proxy start

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/config_flow.py
custom_components/alexa_media/manifest.json
poetry.lock
pyproject.toml

Store mac_dms in the config. This should reduce the frequency of reauth
requirements if registration is failing. This does not remove the requirement for
Amazon to provide a valid mac_dms token at least once. Users who are
unable to receive a valid mac_dms token will need to use the unsupported
3.x series.
closes #1620

fix: store and reuse mac_dms between sessions

---

custom_components/alexa_media/sensor.py

Updated Code to add native_unit_of_measurement and device_class. Now the displayed temperature will be as per global  preferences set by user in Settings->System->General

Fix Temperature always showing Celsius

---

custom_components/alexa_media/notify.py

As proposed by #1738, this PR sets the default data value of the notify service `type` to `tts`.
Closes #1738

Set default data `type` for notify to `tts`

---

custom_components/alexa_media/manifest.json
poetry.lock
pyproject.toml

Bumps alexapy to 1.26.4
closes #1735

fix: handle None responses in clear_history

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/alexa_entity.py
custom_components/alexa_media/binary_sensor.py
custom_components/alexa_media/const.py

Hi,
implemented support for ZigBee Door/Window opening sensors.
This sensor is connected as binary_sensor entity to Home Assistant.
An example of Appliance Details of my sensor:
[contact_sensor.txt](https://github.com/custom-components/alexa_media_player/files/9812176/contact_sensor.txt)
`detectionState` is the capability holding the opened/closed state with text values DETECTED and NOT_DETECTED (for opened and closed states respectively)

Add ZigBee contact sensors support

---

custom_components/alexa_media/config_flow.py

The get_url command would throw an exception even when hass_url was provided through the form.
This would end up ignoring the hass_url input and result in a form loop.
Thanks to @String-656 for testing and discovering this.
closes #1727

fix: fix misconfigured HA url overriding url input

---

custom_components/alexa_media/sensor.py

This addresses the next_alarm filling up the database.
closes #1867

fix: exclude alarm json data from database

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/sensor.py

Amazon stopped sending `NOTIFICATION_UPDATE` messages (at least for specific accounts, discussion in #1971)
This PR also adds a small delay in order to get updated data from the API.
These changes are proposed to the following accounts:
- amazon.it
- amazon.de
- amazon.com.au
The only current limitation is that Alexa commands must be sent ~10 seconds apart in order to update the sensors, but feedback is greatly appreciated.

Change sensor updating trigger to PUSH_ACTIVITY

---

custom_components/alexa_media/media_player.py

The situation should be remedied with an async task. To be on the safe side, I have included the trigger for creating the `www` folder.
Fix: #2032

Fix: FileNotFoundError folder `www` (#2032)

---

.pre-commit-config.yaml
custom_components/alexa_media/__init__.py
custom_components/alexa_media/config_flow.py
custom_components/alexa_media/manifest.json
custom_components/alexa_media/media_player.py
custom_components/alexa_media/sensor.py
custom_components/alexa_media/services.yaml
custom_components/alexa_media/strings.json
custom_components/alexa_media/translations/en.json
poetry.lock
pyproject.toml

This should restore push updates.
Also includes dependency updates.
closes https://github.com/custom-components/alexa_media_player/issues/1953
closes https://github.com/custom-components/alexa_media_player/issues/1976
closes https://github.com/custom-components/alexa_media_player/issues/1967

fix: add http2 push to replace websocket

---

custom_components/alexa_media/sensor.py

This restores NOTIFICATION_CHANGE events for updating alarms and timers, which Amazon appears to support via HTTP2 notifications. This restores alarm and timer updates via changes in the Alexa app. I've kept PUSH_ACTIVITY as well as there does not seem to be any downside in responding to both event types and Amazon may be inconsistent in their implementation across different regions. 
Partial revert of 8f0dfa2 to restore NOTIFICATION_CHANGE functionality for timers and alarms.

Restore NOTIFICATION_CHANGE

---

.pre-commit-config.yaml
custom_components/alexa_media/manifest.json
poetry.lock
pyproject.toml

The http2 stream is sensitive to auth token errors. Instead of declaring a bad login immediately, include one attempt to refresh auth tokens. This may help reduce the frequency of reauth requests but is not guaranteed.
closes #2053

fix: try to refresh tokens when http2 auth error

---

custom_components/alexa_media/alexa_entity.py

Sengled Bluetooth bulbs were returning false from the `is_local` method and therefore were not being added to Home Assistant. Adding Sengled bulbs to the fix already established for Ledvance bulbs fixes the issue and allows Sengled bulbs to be added to Home Assistant when Include devices connected via Echo is checked in the configuration options window.
Fixes #2031

feat: add Sengled Bluetooth bulbs to local Bluetooth check

---

custom_components/alexa_media/media_player.py
hacs.json

Fixes change in 2024.1 for supported features.
Fixes https://github.com/alandtse/alexa_media_player/issues/2149

fix: fix media player supported features for HA beta

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/alexa_entity.py
custom_components/alexa_media/switch.py

This feature allows the user to control Amazon Smart Plugs from the Alexa Media Player integration via switches in Home Assistant.
The feature is valuable since these devices cannot be added to Home Assistant and require complex workarounds.  For example, one implementation requires the use of various plugins used in conjunction (VoiceMonkey for routine triggers, Node-RED for state management and HTTP request methods, and Emulated Hue for state synchronization).

feat: add support for Amazon Smart Plug

---

custom_components/alexa_media/light.py

I coded the changes below. Then when I went to test them, I found that the 1 of the lights that used to connect via Alexa was dead and I am unable to find where I put the other one (embarrassing). I don't normally use lights via Alexa, I just had them from some previous iterations of things I was working on.
So .... if people would like to test and report back, I can try to refine as needed. However, @alandtse, I'd totally understand if you just want to remove/close this PR since it is untested. Sorry.
This PR fixes the deprecated constants, but also changes to use kelvin behind the scenes since that is what the light entities now use and there isn't an easy way to replace the deprecated constants and keep using mireds.

fix: fix deprecated light constants and change to kelvin

---

custom_components/alexa_media/alexa_entity.py

This adds Alexa local switches as switches in addition to smart plugs. This also removes the requirement that local switches and plugs be Amazon-branded.  This allows Home Assistant to control things like [Sengled](https://www.amazon.com/Sengled-Plug-Compatible-Bluetooth-Required/dp/B093F6ZXYY) and other Bluetooth mesh plugs and switches directly connected to an Alexa device.

feat: Add support for non-Amazon switches and plugs

---

custom_components/alexa_media/alexa_entity.py

feat: handle SMARTPLUG as lightswitch when defined in Alexa app as type "LIGHT" (ie. SONOFF ZBMINI Extreme Zigbee switches or real smart plugs when used for lamps)

Handle SMARTPLUG as lightswitch when defined in Alexa app as type "LIGHT"

---

custom_components/alexa_media/helpers.py

Fixes
```
2024-05-04 14:17:07.813 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' accesses hass.helpers.instance_id. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from instance_id directly at custom_components/alexa_media/helpers.py, line 274: uuid = await hass.helpers.instance_id.async_get(), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
```
Partially fixes: https://github.com/alandtse/alexa_media_player/issues/2239

fix: fix instance_id deprecation

---

custom_components/alexa_media/alexa_entity.py

fix: commit e3da18b to support switches as lights (if redeclared that way in the Alexa app) was incomplete due to conflicting change in commit 2344bcf (#2204)

fix: fix lights being identified as switches (#2204)

---

custom_components/alexa_media/__init__.py

This seems to resolve Issue #2283 (638 await hass.config_entries.async_forward_entry_setups)

fix: Raise ConfigEntryNotReady on timeout exception

---

custom_components/alexa_media/config_flow.py

Line 808 should be: default=self.config.get(CONF_QUEUE_DELAY, 1.5),
Line 812 should be default=self.config.get(CONF-EXTENDED_ENTITY_DISCOVERY, 60),

fix: fix AttributeError for 'AlexaMediaFlowHandler'

---

custom_components/alexa_media/config_flow.py

Three fixes/changes:
```
def async_get_options_flow(
config_entry: config_entries.ConfigEntry,
) -> config_entries.OptionsFlow:
```
```
def __init__(self, config_entry: config_entries.ConfigEntry) -> None:
```
and `default=self.config_entry.data.get()` for all options.

fix: use `config_flow` in OptionsFlow Handler

---

custom_components/alexa_media/__init__.py

hass.data[DATA_ALEXAMEDIA]["accounts"].setdefault() "options": {}
Changed config_entry.options.get() to config_entry.data.get()

fix: fix async request refresh

---

custom_components/alexa_media/sensor.py

This change adds the name of a timer to the timer entity attribute list. This is similar to how reminder titles show up on Reminder entities.

feat: add timer label to Timer sensor attributes

---

custom_components/alexa_media/sensor.py

Fix issues #2306 and #2264 - error `alexa_media' calls hass.bus.async_fire from a thread other than the event loop` when alarms are dismissed or snoozed.

fix: add callback decorator to hide threading warning

---

custom_components/alexa_media/__init__.py

fix: use async_create for notification #2380 failed to address hass.components.persistent_notification.async_dismiss on line 1320 
See also #2382 
Styled as per hacs integration [PR #3528 Replace deprecated hass.components usage](https://github.com/hacs/integration/pull/3528/files#top)

fix: replace deprecated hass.components usage

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.pre-commit-config.yaml
custom_components/alexa_media/__init__.py
custom_components/alexa_media/manifest.json
custom_components/alexa_media/sensor.py
poetry.lock
pyproject.toml

Critical to fix all issues related to nom .com domains.
Fixes #2433, #2430, #2429, #2427, #2426, #2418, #2407

fix: bump alexapy to 1.28.2

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.pre-commit-config.yaml
custom_components/alexa_media/__init__.py
custom_components/alexa_media/manifest.json
custom_components/alexa_media/sensor.py
poetry.lock
pyproject.toml

* bump alexapy to 1.28.2
* style: auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
* style: auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
* bump python to 3.11 in devcontainer
* bump python to 3.11 in devcontainer
* bump dockerfile to use python 3.11
* update devcontainer and poetry config
---------

fix: bump alexapy to 1.28.2 (#2434)

---

custom_components/alexa_media/__init__.py

Delete pickle file when removing config entry as it's no longer needed and can cause issues when re-adding the integration entry.

fix: delete cookiefile when removing config entry

---

custom_components/alexa_media/__init__.py

Check if AlexaLogin.delete_cookiefile exists before trying to call.
Fixes issue [#2470](https://github.com/alandtse/alexa_media_player/issues/2470)

fix: 'AlexaLogin' object has no attribute 'delete_cookiefile'

---

custom_components/alexa_media/__init__.py

* Update __init__.py
Added `if callable(getattr(os,'delete_cookiefile', None)):` for compatibility with alexapy<=1.28.2
* Update __init__.py
Class was wrong
Needs to be `AlexaLogin,'delete_cookiefile'`
* style: auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
---------

fix: 'AlexaLogin' object has no attribute 'delete_cookiefile' (#2471)

---

custom_components/alexa_media/config_flow.py

replace hass.components.persistent_notification.async_dismiss with async_diismiss_persistent_notification
addresses deprecated warning in issue in #2467

fix: fix deprecated hass.components use

---

custom_components/alexa_media/__init__.py

Process `include_devices` and `exclude_devices` strings as CSV lists.
Fixes issue #2477

fix: process include/exclude devices

---

custom_components/alexa_media/__init__.py

Add `async_remove_entry` and move cookiefile deletion from `async_unload_entry` to `async_remove_entry`.

fix: delete cookiefile only with `remove_entry`

---

custom_components/alexa_media/alexa_entity.py
custom_components/alexa_media/sensor.py

Fixes the 18 month old issue [Amazon Thermostat reports incorrect temperature #1890](https://github.com/alandtse/alexa_media_player/issues/1890)
Alexa temperature sensors were being hardcoded to `UnitOfTemperature.CELSIUS` thus preventing using sensors with FAHRENHEIT as their native unit.  These changes now correctly retrieve and use `scale` from the `"Alexa.TemperatureSensor", "temperature"` JSON string that Amazon issues in data refreshes: `parse_temperature_from_coordinator: {'value': 24.1, 'scale': 'CELSIUS'}`

fix: fix temperature native_unit_of_measurement

---

custom_components/alexa_media/media_player.py

This addition will allow scripts/automations which reference the `notify.alexa_media_last_called` service or the templated `sensor.last_alexa` sensor to wait for this event to fire before proceeding with their actions.  Previously, everyone was using a hard coded delay to ensure the update last_called had finished.  I had tried watching timestamps but this was only reliable when the timestamp actually changed which sometimes did not happen.  With this feature the reaction time to actions will be a variable delay yet reliable.  I've implemented this with a timeout on the wait for event and if it times out, I bypass all the notify/TTS actions.

feat: fire "alexa_media_last_called_event" after update

---

custom_components/alexa_media/media_player.py

Closes #2283
PR #2336 only addressed loading the media_player component. 
This adds the same code change to media_player.py where switch, sensor, light, etc. components are loaded.

fix: raise ConfigEntryNotReady on timeout

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/config_flow.py

`in_progess_instances` -> `in_progress_instances`

fix: fix typo in in_progress_instances

---

custom_components/alexa_media/helpers.py
custom_components/alexa_media/media_player.py

After uninstalling the Alexa Media Player integration, Home Assistant still attempts to update `media_player` entities associated with the removed integration. These entities try to access the `accounts` data structure within `hass.data[DATA_ALEXAMEDIA]`, which no longer exists post-removal. This leads to unhandled `KeyError` exceptions, causing repetitive error logs and potential instability.
These changes are essential in the following scenarios:
- **Integration Removal**: When users uninstall the Alexa Media Player integration, ensuring that no residual entities attempt to access its data.
- **Error Prevention**: To eliminate `KeyError: 'accounts'` exceptions that occur due to attempts to access removed data structures.
To prevent these errors, the codebase has been modified to include …

fix: fix KeyError 'accounts' after uninstallation

---

custom_components/alexa_media/__init__.py

1. **Deprecation Compliance:**   By replacing `async_load_platform` with `async_forward_entry_setups`, the integration adheres to Home Assistant's evolving architecture, ensuring long-term compatibility and reducing the risk of integration breakage in future updates.
2. **Performance Enhancement:**   Loading multiple platforms concurrently minimizes the time taken for the setup process, leading to a more responsive and efficient integration, especially beneficial for users with numerous Alexa devices.
3. **Maintainability and Readability:**   Consolidating platform initialization into a single, clear method call simplifies the codebase, making it easier for future developers to understand and maintain the integration.
4. **Robust Error Handling:**   Enhanced `try-except` blocks around …

fix: deprecate `async_load_platform`

---

custom_components/alexa_media/__init__.py

In Home Assistant 2024, applying the `@util.Throttle` decorator to asynchronous functions is discouraged because it was originally designed for synchronous functions. Using it on async functions can lead to unexpected behavior, including blocking the event loop, which hampers the integration's performance and responsiveness.
**Problem:**
The `@util.Throttle` decorator restricts how frequently a function can be called. However, when used with asynchronous functions (`async def`), it fails to properly handle coroutines, leading to potential over-execution or missed executions. This disrupts the integration's ability to manage asynchronous tasks efficiently, resulting in performance degradation or inconsistent states.
**Solution:**
Replace the `@util.Throttle` decorator with a custom, …

fix: remove @util.Throttle use

---

custom_components/alexa_media/helpers.py

Iterate on a copy of the existing_serials rather than extend the list being iterated causing infinite iteration
Fixes #2579

fix: fix infinite loop and memory exhaustion

---

CHANGELOG.md
custom_components/alexa_media/const.py
custom_components/alexa_media/manifest.json
poetry.lock
pyproject.toml

tested in local dev instance that login loop is indeed fixed with the bump
addresses the following
https://gitlab.com/keatontaylor/alexapy/-/releases/v1.29.3
mapped in this repo as
https://github.com/alandtse/alexa_media_player/issues/2514
https://github.com/alandtse/alexa_media_player/issues/2515

fix: bump alexapy to 1.29.3

---

custom_components/alexa_media/alarm_control_panel.py

Also directly imports `AlarmControlPanelEntity` since the minimum required HA version already has this implemented.
Closes #2655

fix: use AlarmControlPanelState constants

---

custom_components/alexa_media/alarm_control_panel.py

fix: use AlarmControlPanelState constants (#2657)

---

custom_components/alexa_media/media_player.py

This cleans up a media_player DEBUG log entry.
Before:
```
DEBUG (MainThread) [custom_components.alexa_media.media_player] d****l@b******a: Refreshing <entity unknown.unknown=unknown>
```
After:
```
DEBUG (MainThread) [custom_components.alexa_media.media_player] d****l@b******a: Refreshing: Garage Echo Dot
```

fix: Refreshing <entity unknown.unknown=unknown> in debug log

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/strings.json

YAML configuration is deprecated. Users must manually remove `alexa_media` from `configuration.yaml` file and add the integration via UI to avoid warning messages and future failure.
BREAKING CHANGE: Deprecate YAML configuration

fix!: deprecate YAML configuration

---

custom_components/alexa_media/strings.json

Changed: 
- "unable_to_connect_hass_url"
- "otp_secret"
- "hass_url"
- "public_url"
- "include_devices"
- "exclude_devices"
- "scan_interval"
- "queue_delay"
- "proxy_warning"
- "totp_register"
"registered"
"description"
- "options": "data":
"public_url"
"include_devices"
"exclude_devices"
"scan_interval"
"queue_delay"

fix: change strings descriptions

---

custom_components/alexa_media/alexa_entity.py

Force "TestVendor" in the `is_local` check to return `False` since the entities discovered by Echo devices via Matter discovery are duplicates of already existing HA entities.
Fixes issue #2709

fix: home-assistant-matter-hub duplicated entities

---

custom_components/alexa_media/const.py
custom_components/alexa_media/media_player.py

This clearly conveys to the users that the inability to stream music is not a problem with the integration or home assistant but instead something that Amazon doesn't allow. It also add media_type argument to the async_play_tts_cloud_say function to differentiate the error message for when it is a simple TTS message being sent or music

fix: Clear error message for music streaming

---

custom_components/alexa_media/const.py
custom_components/alexa_media/media_player.py

Fixes the broken TTS action in Home Assistant that was broken in 5.0.3
TTS is defined as media_type music by the TTS component in Home Assistant which resulted in breaking the tts speak action. However, the async_speak function in the TTS component in HA always sets ATTR_MEDIA_ANNOUNCE to true in order to differentiate it from music (https://github.com/home-assistant/core/blob/b46392041f36cc932d0a12eb43af20ecfb7f25db/homeassistant/components/tts/__init__.py#L475) which is now properly implemented.

fix: TTS Speak Action in Home Assistant

---

custom_components/alexa_media/alexa_entity.py

Reintroduces Amazon manufactured devices to be exposed by the integration.  This is especially useful for Amazon Smart Plugs which cannot be added to Home Assistant via any other means.

feat: readd support for Amazon devices

---

custom_components/alexa_media/config_flow.py

This allows users to enter a space to clear the previous entry and we need to change the string from " " to "".
This fixes issue #2556 #2751

fix: Remove leading/trailing spaces from include_devices, exclude_devices

---

custom_components/alexa_media/alexa_entity.py

Should fix #2756 but cannot confirm since I do not have an Amazon air quality monitor.

fix: restore Amazon air quality monitor entities

---

custom_components/alexa_media/media_player.py

This saves the current volume level in new attribute `previous_volume` before changing the volume level.
See discussion #2765

feat: add new attribute: `previous_volume`

---

custom_components/alexa_media/config_flow.py

Make #2748 compatible with Home Assistant version < 2024.12 and be more consistent in the implementation of https://developers.home-assistant.io/blog/2024/11/12/options-flow

fix: Optimize OptionsFlow (#2748)

---

custom_components/alexa_media/alexa_entity.py

This is an entirely untested take on @danielbrunt57's idea from https://github.com/alandtse/alexa_media_player/issues/2709#issuecomment-2511443731.
I do not own any Alexa devices and have no means to run or test this, hence draft. My incentive for making this PR is to allow home-assistant-matter-hub to correctly report bridged device vendor names (which should be the vendor of the device, not the bridge), which would invalidate the existing workaround.
Prior discussion: https://github.com/alandtse/alexa_media_player/issues/2709
Prior PR: https://github.com/alandtse/alexa_media_player/pull/2730

feat: Detect HA matter bridge association

---

custom_components/alexa_media/__init__.py
custom_components/alexa_media/helpers.py
custom_components/alexa_media/media_player.py

Supports `NotifyNowPlayingUpdated` pushes, which are not yet supported in AMP. This will prevent frequent calls to `alexa_api.get_state()`, which was causing errors. This will likely fix #2821 .

fix: Supports `NotifyNowPlayingUpdated` pushes

---

custom_components/alexa_media/media_player.py

This is related to #2827
- Fixed an issue where the throttle was unnecessarily applied when `(previous|next)_track` occurred, preventing proper processing.
- Processed `player_info` acquisition processing by "mediaReferenceId" more strictly.
- Suppressed unnecessary `get_state()` calls.

fix: (previous|next)_track handling

---

custom_components/alexa_media/media_player.py

According to the [Alexa SSML documentation](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#h3_converting_mp3), the `-write_xing 0` flag must be used when generating MP3 files to ensure compatibility with Alexa.
This change adds the necessary FFmpeg flag during MP3 creation to produce files that meet Alexa's playback requirements.

fix: Ensure Alexa-Compatible MP3 Output Using FFmpeg Flag
